#!/bin/bash
# =============================================================================
# hermes_setup.sh — bootstrap Hermes Agent (by Nous Research) inside the
# Railway "free VPS" container and start the Telegram messaging gateway.
#
# Triggered automatically by /startup.sh when HERMES_AUTOSTART=true, or run it
# manually from the desktop terminal:
#     bash /opt/hermes_setup.sh
#
# What it does:
#   1. Installs system deps needed by the official Hermes installer.
#   2. Installs Hermes with the official one-line installer (curl ... install.sh).
#   3. Writes a minimal ~/.hermes/config.yaml (provider key + Telegram token +
#      allowlist) from Railway environment variables.
#   4. Starts `hermes gateway` with nohup and logs to /var/log/hermes_gateway.log
#
# Required environment variables (set these in Railway -> Variables):
#   OPENROUTER_API_KEY  - LLM API key (OpenRouter/OpenAI/Google etc.)
#   TELEGRAM_BOT_TOKEN  - bot token from @BotFather
# Optional environment variables:
#   HERMES_MODEL        - model id, default: openrouter/openai/gpt-4o-mini
#   HERMES_BASE_URL     - OpenAI-compatible base URL (if not OpenRouter)
#   HERMES_ALLOWED_USERS - comma-separated Telegram user ids; default: allow all
# =============================================================================
set -e

LOG=/var/log/hermes_setup.log
exec > >(tee -a "$LOG") 2>&1

echo "=============================================="
echo " Hermes Agent bootstrap started: $(date)"
echo "=============================================="

# ---- Sanity checks ----------------------------------------------------------
if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
    echo "[!] TELEGRAM_BOT_TOKEN is not set. Skipping Hermes setup."
    echo "    Set it (plus OPENROUTER_API_KEY) in Railway -> Variables,"
    echo "    set HERMES_AUTOSTART=true, then redeploy."
    exit 0
fi

if [ -z "$OPENROUTER_API_KEY" ]; then
    echo "[!] OPENROUTER_API_KEY is not set. Skipping Hermes setup."
    exit 0
fi

# ---- 1. System dependencies -------------------------------------------------
echo "[1/5] Installing system dependencies..."
apt-get update -y
apt-get install -y --no-install-recommends \
    curl \
    xz-utils \
    bzip2 \
    build-essential \
    libffi-dev \
    libssl-dev \
    python3-dev \
    ripgrep \
    ffmpeg \
    jq

# ---- 2. Install Hermes Agent (official installer) ----------------------------
echo "[2/5] Installing Hermes Agent..."
export HOME=/root
# Installer writes the 'hermes' launcher to ~/.local/bin and the repo to ~/.hermes/
curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash || \
curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh | bash
export PATH="$HOME/.local/bin:$PATH"

echo "[3/5] Verifying install..."
hermes --version || true

# ---- 3. Write minimal config ------------------------------------------------
echo "[4/5] Writing ~/.hermes/config.yaml ..."
mkdir -p ~/.hermes

MODEL="${HERMES_MODEL:-openrouter/openai/gpt-4o-mini}"
BASE_URL="${HERMES_BASE_URL:-https://openrouter.ai/api/v1}"
ALLOWED="${HERMES_ALLOWED_USERS:-}"

cat > ~/.hermes/config.yaml <<YAML
# Generated by hermes_setup.sh on $(date)
model:
  default: ${MODEL}
  provider: openrouter
  base_url: ${BASE_URL}
  api_key: ${OPENROUTER_API_KEY}
YAML

if [ -n "$ALLOWED" ]; then
    cat >> ~/.hermes/config.yaml <<YAML

gateway:
  platforms:
    telegram:
      bot_token: ${TELEGRAM_BOT_TOKEN}
      allowed_users:
YAML
    # YAML list entries
    echo "${ALLOWED}" | tr ',' '\n' | while read -r uid; do
        [ -n "$uid" ] && echo "        - ${uid}"
    done >> ~/.hermes/config.yaml
else
    cat >> ~/.hermes/config.yaml <<YAML

gateway:
  platforms:
    telegram:
      bot_token: ${TELEGRAM_BOT_TOKEN}
      allow_all_users: true
YAML
fi

cat > ~/.hermes/.env <<ENV
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
ENV

echo "Config written:"
sed -E 's/(api_key|bot_token): .*/\1: [REDACTED]/' ~/.hermes/config.yaml

# ---- 4. Start Telegram gateway ----------------------------------------------
echo "[5/5] Starting Hermes gateway..."
# First run may do first-time init; keep it alive in the background.
nohup hermes gateway > /var/log/hermes_gateway.log 2>&1 &
disown || true
sleep 5

echo "=============================================="
echo " Hermes bootstrap done: $(date)"
echo " Gateway log : /var/log/hermes_gateway.log"
echo " Setup log   : $LOG"
echo " Check       : tail -f /var/log/hermes_gateway.log"
echo "=============================================="